# Generated by Django 6.0.4 on 2026-04-13 01:11

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=article.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('text', 'Text'), ('youtube', 'YouTube')], max_length=20),
        ),
    ]
