# Generated by Django 6.0.4 on 2026-04-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_mediaasset_caption_alter_mediaasset_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content_data',
            field=models.JSONField(help_text='Stores structured text and interactive element markers'),
        ),
    ]
